### ISSUE TITLE
Added, didn't work, feel sad, JsZip something

### ISSUE THREAD

**Issue by PhilAndrew** [lihaoyi/utest#59]
" (C:\Users\philip\.ivy2\cache\org.webjars\jszip\jars\jszip-2.4.0.jar#META-INF/resources/webjars/jszip/2.4.0/jszip.min.js#12)
        at scala.sys.package$.error(package.scala:27)
        at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:168)
        at org.scalajs.jsenv.rhino.RhinoJSEnv$Runner.run(RhinoJSEnv.scala:60)
        at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:64)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:453)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:438)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (test:loadedTestFrameworks) Exception while running JS code: TypeError: Cannot set property "JSZip" of undefined to "
[error] function c(a, b) {
[error]     return this instanceof c ? (this.files = {}, this.comment = null, this.root = "", a && this.load(a, b), void (this.clone = funct
ion () {
[error]         var a = new c();
[error]         for (var b in this) {
[error]             "function" != typeof this[b] && (a[b] = this[b]);
[error]         }
[error]         return a;
[error]     })) : new c(a, b);
[error] }
[error] " (C:\Users\philip\.ivy2\cache\org.webjars\jszip\jars\jszip-2.4.0.jar#META-INF/resources/webjars/jszip/2.4.0/jszip.min.js#12)
[error] Total time: 3 s, completed Feb 24, 2015 5:42:38 PM

C:\home\projects\shape\workbench-example-app-master>

**Comment by lihaoyi** [comment]
Not sure what's going wrong; perhaps try asking on the Scala.js gitter channel?
