### ISSUE TITLE
Stack traces aren't being cutoff

### ISSUE THREAD

**Issue by japgolly** [lihaoyi/utest#60]
Really, really long stack traces.

I've tried this with
- μTest 0.3.0
- Scala.JS 0.6.0 and 0.6.1
- PhantomJS 1.9.8 and 2.0.0

With Phantom.JS 2.0.0 it's like this:

```
[info]        java.lang.AssertionError: assertion failed
[info]  at createException__p1__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:60630:25)(Unknown Source)
[info]  at fillInStackTrace__jl_Throwable (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85746:78)(Unknown Source)
[info]  at init___T__jl_Throwable (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85843:38)(Unknown Source)
[info]  at init___T (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:97597:59)(Unknown Source)
[info]  at init___O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:105504:54)(Unknown Source)
[info]  at assert__Z__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:99568:53)(Unknown Source)
[info]  at Lxxx_webapp_base_test_BaseTestUtil$class__assertEq__Lxxx_webapp_base_test_BaseTestUtil__s_Option__O__O__Lscalaz_Equal__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:33247:39)(Unknown Source)
[info]  at Lxxx_webapp_base_test_BaseTestUtil$class__assertEq__Lxxx_webapp_base_test_BaseTestUtil__T__O__O__Lscalaz_Equal__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:33213:141)(Unknown Source)
[info]  at apply__T2__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:157742:136)(Unknown Source)
[info]  at apply__O__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:157729:20)(Unknown Source)
[info]  at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:86795:72(Unknown Source)
[info]  at apply__O__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:101839:23)(Unknown Source)
[info]  at sc_IndexedSeqOptimized$class__foreach__sc_IndexedSeqOptimized__F1__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:55520:18)(Unknown Source)
[info]  at foreach__F1__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:237158:81)(Unknown Source)
[info]  at foreach__F1__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:86793:32)(Unknown Source)
[info]  at xxx$webapp$client$app$ui$xxx$LogicTest$$anonfun$$anonfun$$anonfun$$test$1__Lxxx_webapp_base_data_xxx__Lxxx_webapp_client_app_ui_xxx_xxx$xxx__F1__sc_Seq__Lscalaz_Equal__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:157521:22)(Unknown Source)
[info]  at apply__T2 (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:157592:220)(Unknown Source)
[info]  at apply__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:157570:24)(Unknown Source)
[info]  at run__sci_List__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:51154:53)(Unknown Source)
[info]  at run__sci_List__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:51150:100)(Unknown Source)
[info]  at run__sci_List__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:51150:100)(Unknown Source)
[info]  at run__sci_List__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:51150:100)(Unknown Source)
[info]  at apply__s_Option__s_util_Try (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174952:195)(Unknown Source)
[info]  at apply__O__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174947:42)(Unknown Source)
[info]  at map__F1__s_util_Try (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:199301:65)(Unknown Source)
[info]  at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:53438:41(Unknown Source)
[info]  at apply__O__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:101839:23)(Unknown Source)
[info]  at run__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:100336:34)(Unknown Source)
[info]  at execute__jl_Runnable__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85056:20)(Unknown Source)
[info]  at executeWithValue__s_util_Try__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:100364:44)(Unknown Source)
[info]  at dispatchOrAddCallback__p2__s_concurrent_impl_CallbackRunnable__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:198841:49)(Unknown Source)
[info]  at onComplete__F1__s_concurrent_ExecutionContext__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:198972:72)(Unknown Source)
[info]  at s_concurrent_Future$class__map__s_concurrent_Future__F1__s_concurrent_ExecutionContext__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:53435:58)(Unknown Source)
[info]  at apply__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174896:136)(Unknown Source)
[info]  at apply__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174909:41)(Unknown Source)
[info]  at liftedTree1$1__p1__s_util_Try (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:86529:72)(Unknown Source)
[info]  at run__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:86524:50)(Unknown Source)
[info]  at execute__jl_Runnable__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85056:20)(Unknown Source)
[info]  at apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:53598:35)(Unknown Source)
[info]  at runFuture__F2__sc_Seq__sc_Seq__s_concurrent_Future__s_concurrent_ExecutionContext__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:51273:115)(Unknown Source)
[info]  at apply__Lutest_util_Tree__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:175319:124)(Unknown Source)
[info]  at utest$framework$TestTreeSeq$$anonfun$$runChildren$1__sc_Seq__sci_List__I__s_concurrent_Future__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174875:58)(Unknown Source)
[info]  at apply__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174900:142)(Unknown Source)
[info]  at apply__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174909:41)(Unknown Source)
[info]  at liftedTree1$1__p1__s_util_Try (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:86529:72)(Unknown Source)
[info]  at run__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:86524:50)(Unknown Source)
[info]  at execute__jl_Runnable__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85056:20)(Unknown Source)
[info]  at apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:53598:35)(Unknown Source)
[info]  at runFuture__F2__sc_Seq__sc_Seq__s_concurrent_Future__s_concurrent_ExecutionContext__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:51273:115)(Unknown Source)
[info]  at apply__Lutest_util_Tree__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:175319:124)(Unknown Source)
[info]  at utest$framework$TestTreeSeq$$anonfun$$runChildren$1__sc_Seq__sci_List__I__s_concurrent_Future__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174875:58)(Unknown Source)
[info]  at apply__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174900:142)(Unknown Source)
[info]  at apply__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:174909:41)(Unknown Source)
[info]  at liftedTree1$1__p1__s_util_Try (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:86529:72)(Unknown Source)
[info]  at run__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:86524:50)(Unknown Source)
[info]  at execute__jl_Runnable__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85056:20)(Unknown Source)
[info]  at apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:53598:35)(Unknown Source)
[info]  at runFuture__F2__sc_Seq__sc_Seq__s_concurrent_Future__s_concurrent_ExecutionContext__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:51273:115)(Unknown Source)
[info]  at runAsync__F2__sc_Seq__sc_Seq__s_concurrent_ExecutionContext__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:51268:119)(Unknown Source)
[info]  at runUTestTask__sc_Seq__sc_Seq__T__Lsbt_testing_EventHandler__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85268:104)(Unknown Source)
[info]  at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85137:103(Unknown Source)
[info]  at apply__O__O__O__O__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:101959:23)(Unknown Source)
[info]  at apply__T__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:175604:67)(Unknown Source)
[info]  at apply__O__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:175580:44)(Unknown Source)
[info]  at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:56346:59(Unknown Source)
[info]  at apply__O__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:101839:23)(Unknown Source)
[info]  at foreach__F1__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:229849:18)(Unknown Source)
[info]  at sc_TraversableLike$class__map__sc_TraversableLike__F1__scg_CanBuildFrom__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:56344:24)(Unknown Source)
[info]  at map__F1__scg_CanBuildFrom__O (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:229964:96)(Unknown Source)
[info]  at executeInternal__p1__Lsbt_testing_EventHandler__ALsbt_testing_Logger__s_concurrent_Future (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85482:68)(Unknown Source)
[info]  at execute__Lsbt_testing_EventHandler__ALsbt_testing_Logger__F1__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85406:110)(Unknown Source)
[info]  at execute__p2__sjs_js_Dynamic__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:65975:73)(Unknown Source)
[info]  at handleMsgImpl__T__F0__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:65740:42)(Unknown Source)
[info]  at handleMsg__p1__T__V (file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:9385:33)(Unknown Source)
[info]  at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:9272:33(Unknown Source)
[info]  at file:///tmp/phantomjs-launcher-webpage655707619739411965.html:89:15(Unknown Source)
```

With Phantom.JS 1.9.8 it's the same except without the class/method info. So

```
[info]        java.lang.AssertionError: assertion failed
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:60630(Unknown Source)
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85746(Unknown Source)
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:85843(Unknown Source)
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:97597(Unknown Source)
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:105504(Unknown Source)
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:99568(Unknown Source)
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:33247(Unknown Source)
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:33213(Unknown Source)
[info]     at file:///home/golly/xxx/projects/xxx/Code/webapp-client/target/scala-2.11/webapp-client-test-fastopt.js:157742(Unknown Source)
...
```

**Comment by japgolly** [comment]
I've found out why. In [BaseRunner.scala#L61](https://github.com/lihaoyi/utest/blob/master/utest/shared/src/main/scala/utest/runner/BaseRunner.scala#L61), `getClassName` returns `<jscode>` for every stack trace frame.

I also tried and failed with these:
* `.getClass.getName` - returns `java.lang.StackTraceElement` for every frame.
* `.getClass.getSimpleName` - returns `StackTraceElement` for every frame.
* `.getClass.getCanonicalName` - not implemented in SJS.
* `.getClass.getTypeName` - not implemented in SJS.
* `.getClass.getPackage.getName` - not implemented in SJS.

**Comment by sjrd** [comment]
`.getClassName` is the right thing. It has *nothing* to do with `getClass.getName`. See [StackTraceElement](http://docs.oracle.com/javase/7/docs/api/java/lang/StackTraceElement.html)

However `getClassName` is quite unreliable. We basically try to recover this information from the VM's stack trace, which is a string with a format varying from VM to VM, and from version to version ^^. The recovery heuristics are in [StackTrace](https://github.com/scala-js/scala-js/blob/master/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala). Sometimes the VM's stack trace doesn't even contain the class name, in which case there's nothing we can do.

`getMethodName` is pretty reliable. `getFileName` as well, but doesn't apply source maps in all VMs, such as PhantomJS.

The most reliable way to cut such a stack trace is to have a method with a pretty unique and recognizable name, which you can identify with `getMethodName`.

**Comment by lihaoyi** [comment]
This should be fixed in master by https://github.com/lihaoyi/utest/commit/2810c625c6a5d98476c50d4d5a69f480c42933e3#diff-910ec1813f88878eb7ec68c377062fb0 and the follow up https://github.com/lihaoyi/utest/commit/f38bd2b9c7e404a5eee81cebcfe2fdc81233f49d#diff-910ec1813f88878eb7ec68c377062fb0, which uses `getClassName` and `getMethodName` to decide on stack trace cutoff, and `@noinline` to try and make sure Scala.js doesn't make the marker methods disappear
