### ISSUE TITLE
Exception when running testsuite from Intellij IDEA

### ISSUE THREAD

**Issue by jn73** [lihaoyi/utest#66]
When i run the following testsuite from within Intellij:

``` scala
package se.oobo.validation

import utest._
import utest.ExecutionContext.RunNow

object ValidationTest extends TestSuite {
  override def tests = TestSuite {
    'sometest - {
      val x = 3
      val y = 2
      assert(x != y)
    }
  }
}
```

...i get this exception:

Exception in thread "main" java.lang.IllegalStateException: Test that returns Future must be run asynchronously in Scala.js, see TestTreeSeq::runAsync
    at utest.PlatformShims$.await(PlatformShims.scala:18)
    at utest.framework.TestTreeSeq.run(Model.scala:141)
    at org.jetbrains.plugins.scala.testingSupport.uTest.UTestRunner.runTestSuites(UTestRunner.java:198)
    at org.jetbrains.plugins.scala.testingSupport.uTest.UTestRunner.main(UTestRunner.java:258)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 1

Any ideas?

**Comment by rabejens** [comment]
I have the same problem. No ideas?

**Comment by kelebra** [comment]
Me too, would be thankful for solution.

**Comment by sLite** [comment]
Same here :)

**Comment by sLite** [comment]
I think the reason lies within IntelliJ Scala Plugin. It doesn't use the SBT testrunner and runs the test manually.

see https://github.com/JetBrains/intellij-scala/blob/829c1de5b1e421755af1cefb5ad2e390f5c62cf1/Runners/src/org/jetbrains/plugins/scala/testingSupport/uTest/UTestRunner.java#L244

I'm going to open a ticket in the issue tracker.

**Comment by sLite** [comment]
https://youtrack.jetbrains.com/issue/SCL-8972

**Comment by lihaoyi** [comment]
Closing this in favor of https://youtrack.jetbrains.com/issue/SCL-8972. I'm not aware of IntelliJ support *any* Scala.js test running at all, so there's probably not much uTest can do here.
